version: "3.1"

services:
  postgres:
    image: postgres:12.4
    restart: on-failure
    networks:
      - default
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    ports:
      - 5432:5432
    volumes:
      - ./dump:/docker-entrypoint-initdb.d

  voltvector-be:
    image: ghcr.io/pb-coding/voltvector-be
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - default
      - swag_net
    env_file:
      - .env

networks:
  default:
  swag_net:
    external:
      name: swag_net
