version: "3.1"

services:
  postgres:
    image: postgres:12.4
    restart: on-failure
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    ports:
      - 5432:5432
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
